version: '3'
services:
  app:
    container_name: app
    build: .
    ports:
     - "8080:8080"
    depends_on: 
      - redis 
    networks: 
      - backend
   
  redis:
    container_name: redis
    image: redis
    command: [ "redis-server", "--protected-mode", "no" ]
    ports:
      - "6379:6379"
    expose:
      - "6379"  
    networks:
      - backend

networks:
  backend: